trigger:
  branches:
    include:
      - main

variables:
  - group: staging-variable-group

jobs:

  - job: IntegrationTests
    displayName: "Deploy & Integration Tests"

    pool:
      vmImage: "ubuntu-latest"
      name: Default

    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        displayName: "Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)"

      # Install Databricks CLI
      # - script: |
      #     curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
      #   displayName: "Install Databricks CLI"

      # Extract Databricks version to test installation
      - script: |
          databricks version
        displayName: "Get Databricks CLI version"

      # Deploy
      - script: |
          cd default_python
          databricks bundle deploy -t staging
        displayName: "Deploy bundle to environment"
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)

      # Run 
      - script: |
          cd default_python
          databricks bundle run -t staging default_python_job
        displayName: "Run workflow"
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
