trigger:
  branches:
    include:
      - release

variables:
  - group: prod-variable-group

jobs:

  - job: Deploy
    displayName: "Deploy"

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        displayName: "Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)"

      # Install Databricks CLI
      - script: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
        displayName: "Install Databricks CLI"

      # Extract Databricks version to test installation
      - script: |
          databricks version
        displayName: "Get Databricks CLI version"

      # Validate
      - script: |
          cd default_python
          databricks bundle validate -t prod
        displayName: "Validate bundle"
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
          
      # Deploy
      - script: |
          cd default_python
          databricks bundle deploy -t prod --force-lock
        displayName: "Deploy bundle to environment"
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET)
          BUNDLE_VAR_notifications_email_address: $(BUNDLE_VAR_notifications_email_address)
